name: CI

on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Test env
        working-directory: ./tests
        run: |
          npm install

      - name: Install and test backend
        working-directory: ./backend
        run: |
          npm ci
          npm test

      - name: Backend code coverage
        working-directory: ./backend
        run: |
          npm run test:coverage

      - name: Backend code quality
        working-directory: ./backend
        run: |
          npm run lint
